apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: app-slug
spec:
  title: Super Cool App
  icon: https://png.pngtree.com/png-vector/20190927/ourmid/pngtree-lovely-bat-clipart-vector-png-element-png-image_1749074.jpg
  statusInformers:
    - deployment/example-nginx
  ports:
    - serviceName: "example-nginx"
      servicePort: 80
      localPort: 8888
      applicationUrl: "http://example-nginx"
